language: node_js
node_js:
- '6'
before_script:
- npm install -g typescript
- npm install -g istanbul
script:
- npm run compile
- npm run coverage
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: deblock.thomas.62@gmail.com
  api_key:
    secure: 4CXk6sg5UM78KWqzofJ7DjrHx0Fdp+HCtFHS5vsQnBvFnd6dfgBURWDjlApY7B82o97i8jIm4CCfyw8UXh33sBfsNz+TdPgVFe7Ej9QATV882dFO7Hn/S2oeQcNF+ntGFpoPIwLI8VIGkd6EobYj54uwAOXKa+ZyDQsFyh6OmcJ561pijM14nnQd0I7M+zf7NLJjyv1IAGIV5eFuiQi8AYjZMizfEClZkzFGP4en1LOnEcbb96siqAm/1nz87ViIS9Ou1RpuxQh6G6vsU71636CVHm2Uuy/kkGk69iwqB7foyX1Hfp41Sglga28d6nPutfmckmNzw5TcehM8R+gvoHUmI1iDHCd/4FCpEgyI/fxfqjLUAAHx51WHs7nDa8Cjac28fHTLujMuySN6lvEHsLg5u4zcWoAQKrWFL1yOjFiV6NxpoO+agfIfMiOabHU/WSLAPkMXUFjV2TMMKJvwIRNueFOi8xuID2A4QYCpjTeO/stKGbQm/gKVCIsyA5QOvvBW/RdqPetVcF995maWdeyo3PlgXxCSVOBEdN2VXx99ZnGdezzE+j2EusqcJH20ap73Zicg5tpoGOb0uZzAGB3DnVzl1wFfGBGah7q5VIoVvDjiGfcJzrUfglwXUcyq856mlKVMFLnuZEWMTXT6IVQpAPA+5luXViUbeqpD4HU=
  on:
    branch: master
    repo: deblockt/hal-rest-client
